import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FCFDFF" },
  content: { flex: 1, padding: 25, paddingTop: 40 },
  topNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 35,
    marginTop: 10,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButtonCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  headerBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerLogo: {
    backgroundColor: "white",
    borderRadius: 15,
  },
  brandTag: {
    fontWeight: "900",
    color: "#21307A",
    fontSize: 13,
    letterSpacing: 1,
    lineHeight: 14,
  },
  brandSub: {
    fontSize: 9,
    color: "#94A3B8",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  progressContainer: {
    alignItems: "flex-end",
  },
  progressDots: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 2,
  },
  dot: { width: 5, height: 5, borderRadius: 2.5, backgroundColor: "#CBD5E1" },
  activeDot: { backgroundColor: "#21307A", width: 14 },
  stepCounter: {
    fontSize: 9,
    fontWeight: "700",
    color: "#94A3B8",
  },
  blob: { position: "absolute", width: 400, height: 400, borderRadius: 200 },
  mainTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#21307A",
    marginBottom: 25,
    letterSpacing: -0.5,
  },
  setupCard: {
    padding: 20,
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
  },
  form: { gap: 12 },
  input: {
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    color: "#1E293B",
  },
  inputError: { borderColor: "#FDA4AF", backgroundColor: "#FFF1F2" },
  errorText: {
    color: "#E11D48",
    fontSize: 11,
    marginTop: 4,
    marginLeft: 8,
    fontWeight: "600",
  },
  row: { flexDirection: "row", gap: 10 },
  logoPicker: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: "#F8FAFC",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#CBD5E1",
    marginBottom: 10,
  },
  logoPlaceholder: { alignItems: "center" },
  logoPreview: { width: 86, height: 86, borderRadius: 43 },
  logoText: { fontSize: 10, color: "#94A3B8", marginTop: 4, fontWeight: "600" },
  actionBtn: {
    backgroundColor: "#21307A",
    padding: 18,
    borderRadius: 16,
    marginTop: 25,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  disabledBtn: { opacity: 0.7 },
  actionBtnText: { color: "#FFF", fontWeight: "700", fontSize: 16 },
});
